import Head from 'next/head'
import Image from 'next/image'
import Navigation from '../components/shared/Navigation'
import MainInfo from '../components/MainInfo/MainInfo'
import HomeBlog from '../components/HomeBlog/HomeBlog'
import Blog from '../components/Blog/Blog'
// import {getAllPosts} from '../lib/posts-util'
import Contact from '../components/Contact/Contact'
import Experience from '../components/Experience/Experience'
import Projects from './Projects'

import { db } from '../pages/api/firebase-config';
import { collection, getDocs} from 'firebase/firestore';
import { postToJSON } from '../pages/api/firebase-config';

function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <MainInfo />

      <Experience />
      <Projects />
      

      <Blog posts={props.posts} />


      {/* <HomeBlog posts={props.posts} /> */}
      

      <Contact />
      
    </div>
  )
}

export async function getServerSideProps(context)  {
  const postsColectionRef = await getDocs(collection(db, 'posts'))
  const posts = postsColectionRef.docs.map(postToJSON)

  // const posts = postsColectionRef.map(data => ({
    // id: data.id,
    // ...data.data()
  // }))

  return {
    props: { posts }
  }
}

// export function getStaticProps() {
  
//   const allPosts = getAllPosts();

//   return {
//     props: {
//       posts: allPosts
//     }
//   }
// }

export default Home
