import Head from 'next/head'
import Image from 'next/image'
import Navigation from '../components/shared/Navigation'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navigation />
      <main classNameName='bg-blue-700'>
        <h1>Main Content will be here</h1>
      </main>

      
    </div>
  )
}
