import Head from 'next/head'
import Image from 'next/image'
import Navigation from '../components/shared/Navigation'
import MainInfo from '../components/MainInfo/MainInfo'
import HomeBlog from '../components/HomeBlog/HomeBlog'
import {getAllPosts} from '../lib/posts-util'

function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainInfo />

      <HomeBlog posts={props.posts} />
      
    </div>
  )
}

export function getStaticProps() {
  
  const allPosts = getAllPosts();

  return {
    props: {
      posts: allPosts
    }
  }
}

export default Home
